---

- name: Configure storage locations in {{ bareos_root_dir }}/bareos-dir.d/storage/*.conf (Director)
  template:
    src: "storage.conf.j2"
    dest: "{{ bareos_root_dir }}/bareos-dir.d/storage/{{ item.name }}.conf"
    owner: "{{ bareos_owner }}"
    group: "{{ bareos_group }}"
    mode: 0640
  loop: "{{ bareos_remote_storage_locations }}"
  notify: reload bareos-dir
  tags: [bareos-dir]

- name: Configure local {{ bareos_root_dir }}/bareos-sd.d/director/bareos-dir.conf (Director)
  template:
    src: "bareos-dir.conf.j2"
    dest: "{{ bareos_root_dir }}/bareos-sd.d/director/bareos-dir.conf"
    owner: "{{ bareos_owner }}"
    group: "{{ bareos_group }}"
    mode: 0640
  notify: Restart bareos-sd
  tags: [bareos-storage]

- name: Configure messages in {{ bareos_root_dir }}/bareos-dir.d/messages/Standard.conf
  template:
    src: "messages-standard.conf.j2"
    dest: "{{ bareos_root_dir }}/bareos-dir.d/messages/Standard.conf"
    owner: "{{ bareos_owner }}"
    group: "{{ bareos_group }}"
    mode: 0640
  notify: reload bareos-dir
  tags: [bareos-dir]

- name: Configure filesets in {{ bareos_root_dir }}/bareos-dir.d/fileset/*.conf (Director)
  template:
    src: "filesets.conf.j2"
    dest: "{{ bareos_root_dir }}/bareos-dir.d/fileset/{{ item.name }}.conf"
    owner: "{{ bareos_owner }}"
    group: "{{ bareos_group }}"
    mode: 0640
  loop: "{{ bareos_filesets }}"
  notify: reload bareos-dir
  tags: [bareos-dir]

- name: Configure schedules in {{ bareos_root_dir }}/bareos-dir.d/schedule/*.conf (Director)
  template:
    src: "schedule.yml.j2"
    dest: "{{ bareos_root_dir }}/bareos-dir.d/schedule/{{ item.name }}.conf"
    owner: "{{ bareos_owner }}"
    group: "{{ bareos_group }}"
    mode: 0640
  loop: "{{ bareos_schedules }}"
  notify: reload bareos-dir
  tags: [bareos-dir]

- name: Configure client pools in {{ bareos_root_dir }}/bareos-dir.d/pool/*.conf (Director)
  template:
    src: "pools.conf.j2"
    dest: "{{ bareos_root_dir }}/bareos-dir.d/pool/{{ item }}.conf"
    owner: "{{ bareos_owner }}"
    group: "{{ bareos_group }}"
    mode: 0640
  notify: reload bareos-dir
  loop: "{{ groups[bareos_clients_group] }}"
  tags: [add-bareos-client, bareos-dir]

- name: Configure clients in {{ bareos_root_dir }}/bareos-dir.d/client/*.conf (Director)
  template:
    src: "client.conf.j2"
    dest: "{{ bareos_root_dir }}/bareos-dir.d/client/{{ item }}.conf"
  notify: reload bareos-dir
  loop: "{{ groups[bareos_clients_group] }}"
  tags: [add-bareos-client, bareos-dir]

- name: Configure client jobs in {{ bareos_root_dir }}/bareos-dir.d/job/*.conf (Director)
  template:
    src: "jobs.conf.j2"
    dest: "{{ bareos_root_dir }}/bareos-dir.d/job/{{ item }}.conf"
    owner: "{{ bareos_owner }}"
    group: "{{ bareos_group }}"
    mode: 0640
  notify: reload bareos-dir
  loop: "{{ groups[bareos_clients_group] }}"
  tags: [add-bareos-client, bareos-dir]

- name: Configure Maximum Concurrent Jobs in {{ bareos_root_dir }}/bareos-dir.d/director/bareos-dir.conf (Director)
  lineinfile:
    path: "{{ bareos_root_dir }}/bareos-dir.d/director/bareos-dir.conf"
    regexp: "Maximum Concurrent Jobs = [1-9].*"
    line: "Maximum Concurrent Jobs = {{ bareos_storage_max_concurrent_jobs }}"
  notify: reload bareos-dir
  tags: [bareos-dir]

- name: Configure user ACL profiles in {{ bareos_root_dir }}/bareos-dir.d/profile/ (Director)
  template:
    src: acl-profiles.conf.j2
    dest: "{{ bareos_root_dir }}/bareos-dir.d/profile/{{ item }}.conf"
  loop: "{{ groups[bareos_clients_group] }}"
  when: "hostvars[item]['client_acl_allow_hosts'] is defined"
  notify: reload bareos-dir
  tags: [add-bareos-client, bareos-dir, bareos-acl]

- name: Configure users for accessing WebUI in {{ bareos_root_dir }}/bareos-dir.d/console/ (Director)
  template:
    src: acl-users.conf.j2
    dest: "{{ bareos_root_dir }}/bareos-dir.d/console/{{ item }}.conf"
  loop: "{{ groups[bareos_clients_group] }}"
  when: "hostvars[item]['client_acl_allow_hosts'] is defined"
  notify: reload bareos-dir
  tags: [add-bareos-client, bareos-dir, bareos-acl]

- name: Ensure Bareos services are started
  service:
    name: "{{ item }}"
    state: started
  loop:
    - bareos-dir
    - bareos-sd
    - bareos-fd
  tags: [bareos-dir]
