---

- name: Configure storage locations in {{ bareos_root_dir }}/bareos-dir.d/storage/*.conf (Director)
  template:
    src: "storage.conf.j2"
    dest: "{{ bareos_root_dir }}/bareos-dir.d/storage/{{ item.name }}.conf"
    owner: "{{ bareos_owner }}"
    group: "{{ bareos_group }}"
    mode: 0640
  loop: "{{ bareos_remote_storage_locations }}"
  notify: reload bareos-dir
  tags: [bareos-dir]

- name: Configure local {{ bareos_root_dir }}/bareos-sd.d/director/bareos-dir.conf (Director)
  template:
    src: "bareos-dir.conf.j2"
    dest: "{{ bareos_root_dir }}/bareos-sd.d/director/bareos-dir.conf"
    owner: "{{ bareos_owner }}"
    group: "{{ bareos_group }}"
    mode: 0640
  notify: Restart bareos-sd
  tags: [bareos-storage]

- name: Configure messages in {{ bareos_root_dir }}/bareos-dir.d/messages/Standard.conf
  template:
    src: "messages-standard.conf.j2"
    dest: "{{ bareos_root_dir }}/bareos-dir.d/messages/Standard.conf"
    owner: "{{ bareos_owner }}"
    group: "{{ bareos_group }}"
    mode: 0640
  notify: reload bareos-dir
  tags: [bareos-dir]

- name: Configure filesets in {{ bareos_root_dir }}/bareos-dir.d/fileset/*.conf (Director)
  template:
    src: "filesets.conf.j2"
    dest: "{{ bareos_root_dir }}/bareos-dir.d/fileset/{{ item.name }}.conf"
    owner: "{{ bareos_owner }}"
    group: "{{ bareos_group }}"
    mode: 0640
  loop: "{{ bareos_filesets }}"
  notify: reload bareos-dir
  tags: [bareos-dir]

- name: Configure schedules in {{ bareos_root_dir }}/bareos-dir.d/schedule/*.conf (Director)
  template:
    src: "schedule.yml.j2"
    dest: "{{ bareos_root_dir }}/bareos-dir.d/schedule/{{ item.name }}.conf"
    owner: "{{ bareos_owner }}"
    group: "{{ bareos_group }}"
    mode: 0640
  loop: "{{ bareos_schedules }}"
  notify: reload bareos-dir
  tags: [bareos-dir]

- name: Configure pools in {{ bareos_root_dir }}/bareos-dir.d/pool/*.conf (Director)
  template:
    src: "pools.conf.j2"
    dest: "{{ bareos_root_dir }}/bareos-dir.d/pool/{{ item.hostname }}.conf"
    owner: "{{ bareos_owner }}"
    group: "{{ bareos_group }}"
    mode: 0640
  notify: reload bareos-dir
  loop: "{{ bareos_clients }}"
  tags: [bareos-client, bareos-dir]

- name: Configure clients in {{ bareos_root_dir }}/bareos-dir.d/client/*.conf (Director)
  template:
    src: "client.conf.j2"
    dest: "{{ bareos_root_dir }}/bareos-dir.d/client/{{ item.hostname }}.conf"
  notify: reload bareos-dir
  loop: "{{ bareos_clients }}"
  tags: [bareos-client, bareos-dir]

- name: Configure client jobs in {{ bareos_root_dir }}/bareos-dir.d/job/*.conf (Director)
  template:
    src: "jobs.conf.j2"
    dest: "{{ bareos_root_dir }}/bareos-dir.d/job/{{ item.hostname }}.conf"
    owner: "{{ bareos_owner }}"
    group: "{{ bareos_group }}"
    mode: 0640
  notify: reload bareos-dir
  loop: "{{ bareos_clients }}"
  tags: [bareos-client, bareos-dir]

- name: Configure Maximum Concurrent Jobs in {{ bareos_root_dir }}/bareos-dir.d/director/bareos-dir.conf
  lineinfile:
    path: "{{ bareos_root_dir }}/bareos-dir.d/director/bareos-dir.conf"
    regexp: "Maximum Concurrent Jobs = [1-9].*"
    line: "Maximum Concurrent Jobs = {{ bareos_storage_max_concurrent_jobs }}"
  notify: reload bareos-dir

- name: Ensure Bareos services are started
  service:
    name: "{{ item }}"
    state: started
  loop:
    - bareos-dir
    - bareos-sd
    - bareos-fd
