---

- name: Install Bareos packages
  yum:
    name: bareos, bareos-database-postgresql
    state: installed
  register: bareos_initial_installation

- name: Create MySQL database
  shell: su - postgres -c '/usr/lib/bareos/scripts/create_bareos_database postgresql'
  when: bareos_initial_installation.changed

- name: Create initial MySQL tables
  shell: su - postgres -c '/usr/lib/bareos/scripts/make_bareos_tables postgresql'
  when: bareos_initial_installation.changed

- name: Grant MySQL user privileges
  shell: su - postgres -c '/usr/lib/bareos/scripts/grant_bareos_privileges postgresql'
  when: bareos_initial_installation.changed

- name: Change database type to PostgreSQL for catalog resource
  lineinfile:
    path: "{{ bareos_root_dir }}/bareos-dir.d/catalog/MyCatalog.conf"
    regexp: "dbdriver = .*"
    line: "dbdriver = postgresql"
  when: bareos_initial_installation.changed

- name: Enable Bareos services
  service:
    name: "{{ item }}"
    enabled: yes
  loop:
    - 'bareos-dir'
    - 'bareos-sd'
    - 'bareos-fd'
