---

- name: Install Bareos packages
  yum:
    name: bareos, bareos-database-mysql
    state: installed
  register: bareos_initial_installation

- name: Create MySQL database
  command: '/usr/lib/bareos/scripts/create_bareos_database'
  when: bareos_initial_installation.changed

- name: Create initial MySQL tables
  command: "/usr/lib/bareos/scripts/make_bareos_tables"
  when: bareos_initial_installation.changed

- name: Grant MySQL user privileges
  command: "/usr/lib/bareos/scripts/grant_bareos_privileges"
  when: bareos_initial_installation.changed

- name: Enable Bareos firewalld ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - '9101/tcp'
    - '9103/tcp'
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '7'
  # TODO: Fix when conditional via service_facts

- name: Enable Bareos services
  service:
    name: "{{ item }}"
    enabled: yes
  loop:
    - 'bareos-dir'
    - 'bareos-sd'
    - 'bareos-fd'

- name: Download MySQL plugin
  get_url:
    url: "{{ item }}"
    dest: "{{ bareos_plugins_location }}"
    mode: 0755
  loop:
    - "{{ bareos_git_raw }}/fd-plugins/mysql-python/BareosFdMySQLclass.py"
    - "{{ bareos_git_raw }}/fd-plugins/mysql-python/bareos-fd-mysql.py"
