---

- name: Restart bareos-dir
  service:
    name: bareos-dir
    state: restarted

- name: Reload bareos-dir
  command: "echo 'reload' | bconsole"

- name: Restart bareos-fd
  service:
    name: bareos-fd
    state: restarted
